[2024-03-12 11:15:48,219] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: LabDadosExtract.labdados_datascience scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-03-12 11:15:48,229] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: LabDadosExtract.labdados_datascience scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-03-12 11:15:48,229] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-12 11:15:48,230] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-12 11:15:48,230] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-12 11:15:48,251] {taskinstance.py:1377} INFO - Executing <Task(labdadosOperator): labdados_datascience> on 2024-03-11 00:00:00+00:00
[2024-03-12 11:15:48,254] {standard_task_runner.py:52} INFO - Started process 58218 to run task
[2024-03-12 11:15:48,259] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'LabDadosExtract', 'labdados_datascience', 'scheduled__2024-03-11T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/labdados_dag.py', '--cfg-path', '/tmp/tmp5pwtli28', '--error-file', '/tmp/tmp2b2r3tri']
[2024-03-12 11:15:48,260] {standard_task_runner.py:80} INFO - Job 6: Subtask labdados_datascience
[2024-03-12 11:15:48,323] {task_command.py:370} INFO - Running <TaskInstance: LabDadosExtract.labdados_datascience scheduled__2024-03-11T00:00:00+00:00 [running]> on host JuniorLafuente.
[2024-03-12 11:15:48,404] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=LabDadosExtract
AIRFLOW_CTX_TASK_ID=labdados_datascience
AIRFLOW_CTX_EXECUTION_DATE=2024-03-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-11T00:00:00+00:00
[2024-03-12 11:15:48,415] {base.py:68} INFO - Using connection ID 'labdados' for task execution.
[2024-03-12 11:15:48,418] {labdados_hook.py:39} INFO - URL: https://labdados.com/2/tweets/search/recent?query=datascience&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,lang,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2024-03-11T00:00:00.00Z&end_time=2024-03-12T00:00:00.00Z
[2024-03-12 11:15:49,532] {logging_mixin.py:115} INFO - {
    "data": [
        {
            "author_id": "5",
            "conversation_id": "44",
            "created_at": "2024-03-11T20:11:30.967885+0000",
            "edit_history_tweet_ids": [
                83
            ],
            "id": "24",
            "in_reply_to_user_id": "46",
            "lang": "en",
            "public_metrics": {
                "like_count": 63,
                "quote_count": 32,
                "reply_count": 65,
                "retweet_count": 66
            },
            "text": "Tweet fict\u00edcio gerado automaticamente sobre datascience"
        },
        {
            "author_id": "100",
            "conversation_id": "16",
            "created_at": "2024-03-11T05:05:47.870439+0000",
            "edit_history_tweet_ids": [
                58
            ],
            "id": "60",
            "in_reply_to_user_id": "57",
            "lang": "en",
            "public_metrics": {
                "like_count": 78,
                "quote_count": 98,
                "reply_count": 75,
                "retweet_count": 16
            },
            "text": "Um terceiro tweet fict\u00edcio sobre datascience"
        },
        {
            "author_id": "77",
            "conversation_id": "96",
            "created_at": "2024-03-11T22:26:49.141572+0000",
            "edit_history_tweet_ids": [
                59
            ],
            "id": "92",
            "in_reply_to_user_id": "0",
            "lang": "en",
            "public_metrics": {
                "like_count": 85,
                "quote_count": 72,
                "reply_count": 86,
                "retweet_count": 47
            },
            "text": "Tweet fict\u00edcio gerado automaticamente sobre datascience"
        },
        {
            "author_id": "69",
            "conversation_id": "0",
            "created_at": "2024-03-11T01:08:45.846982+0000",
            "edit_history_tweet_ids": [
                8
            ],
            "id": "4",
            "in_reply_to_user_id": "14",
            "lang": "en",
            "public_metrics": {
                "like_count": 88,
                "quote_count": 4,
                "reply_count": 74,
                "retweet_count": 80
            },
            "text": "Tweet fict\u00edcio criado usando intelig\u00eancia artificial para falar sobre datascience"
        },
        {
            "author_id": "57",
            "conversation_id": "91",
            "created_at": "2024-03-11T10:57:18.159823+0000",
            "edit_history_tweet_ids": [
                64
            ],
            "id": "52",
            "in_reply_to_user_id": "43",
            "lang": "en",
            "public_metrics": {
                "like_count": 9,
                "quote_count": 6,
                "reply_count": 26,
                "retweet_count": 33
            },
            "text": "Tweet fict\u00edcio criado usando intelig\u00eancia artificial para falar sobre datascience"
        },
        {
            "author_id": "83",
            "conversation_id": "39",
            "created_at": "2024-03-11T05:27:39.000999+0000",
            "edit_history_tweet_ids": [
                50
            ],
            "id": "78",
            "in_reply_to_user_id": "51",
            "lang": "en",
            "public_metrics": {
                "like_count": 75,
                "quote_count": 42,
                "reply_count": 54,
                "retweet_count": 60
            },
            "text": "Outro tweet fict\u00edcio relacionado a datascience"
        },
        {
            "author_id": "92",
            "conversation_id": "90",
            "created_at": "2024-03-11T21:08:05.266653+0000",
            "edit_history_tweet_ids": [
                31
            ],
            "id": "20",
            "in_reply_to_user_id": "90",
            "lang": "en",
            "public_metrics": {
                "like_count": 58,
                "quote_count": 41,
                "reply_count": 88,
                "retweet_count": 88
            },
            "text": "Este \u00e9 um tweet fict\u00edcio sobre datascience"
        },
        {
            "author_id": "29",
            "conversation_id": "64",
            "created_at": "2024-03-11T11:01:43.282484+0000",
            "edit_history_tweet_ids": [
                30
            ],
            "id": "62",
            "in_reply_to_user_id": "68",
            "lang": "en",
            "public_metrics": {
                "like_count": 4,
                "quote_count": 41,
                "reply_count": 10,
                "retweet_count": 56
            },
            "text": "Um terceiro tweet fict\u00edcio sobre datascience"
        },
        {
            "author_id": "19",
            "conversation_id": "52",
            "created_at": "2024-03-11T21:54:17.082638+0000",
            "edit_history_tweet_ids": [
                9
            ],
            "id": "45",
            "in_reply_to_user_id": "59",
            "lang": "en",
            "public_metrics": {
                "like_count": 2,
                "quote_count": 3,
                "reply_count": 64,
                "retweet_count": 88
            },
            "text": "Tweet fict\u00edcio gerado automaticamente sobre datascience"
        },
        {
            "author_id": "42",
            "conversation_id": "56",
            "created_at": "2024-03-11T14:34:27.832836+0000",
            "edit_history_tweet_ids": [
                10
            ],
            "id": "56",
            "in_reply_to_user_id": "76",
            "lang": "en",
            "public_metrics": {
                "like_count": 65,
                "quote_count": 44,
                "reply_count": 24,
                "retweet_count": 88
            },
            "text": "Um terceiro tweet fict\u00edcio sobre datascience"
        }
    ],
    "includes": {
        "users": [
            {
                "created_at": "2024-03-11T22:53:50.855165+0000",
                "id": "98",
                "name": "User 1",
                "username": "user1"
            },
            {
                "created_at": "2024-03-11T19:51:24.017172+0000",
                "id": "77",
                "name": "User 2",
                "username": "user2"
            },
            {
                "created_at": "2024-03-11T20:05:49.204020+0000",
                "id": "34",
                "name": "User 3",
                "username": "user3"
            },
            {
                "created_at": "2024-03-11T06:39:32.338541+0000",
                "id": "11",
                "name": "User 4",
                "username": "user4"
            },
            {
                "created_at": "2024-03-11T02:11:57.856765+0000",
                "id": "42",
                "name": "User 5",
                "username": "user5"
            },
            {
                "created_at": "2024-03-11T19:16:54.546527+0000",
                "id": "22",
                "name": "User 6",
                "username": "user6"
            },
            {
                "created_at": "2024-03-11T07:01:42.290218+0000",
                "id": "18",
                "name": "User 7",
                "username": "user7"
            },
            {
                "created_at": "2024-03-11T13:03:06.155798+0000",
                "id": "28",
                "name": "User 8",
                "username": "user8"
            },
            {
                "created_at": "2024-03-11T17:48:04.984184+0000",
                "id": "20",
                "name": "User 9",
                "username": "user9"
            },
            {
                "created_at": "2024-03-11T06:38:10.348076+0000",
                "id": "73",
                "name": "User 10",
                "username": "user10"
            }
        ]
    }
}
[2024-03-12 11:15:49,557] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=LabDadosExtract, task_id=labdados_datascience, execution_date=20240311T000000, start_date=20240312T141548, end_date=20240312T141549
[2024-03-12 11:15:49,604] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-12 11:15:49,635] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
